### ISSUE TITLE
Silly question: where is .env?

### ISSUE THREAD

**Issue by atanasj** [MobileCommerceLab/RQDA-RStudio-sshd#3]
This is a silly question. But what exactly is the `.env`? Do I create one in my home folder, or is it something that already exists (if so, I cannot find it). This question is in relation to: 

> Copy the `dot_env_example` file to `.env`, and set the permissions with `chmod 600 .env`

Thanks for your patience.

**Comment by peterstory** [comment]
The .env file contains configurable settings. In this case, the root account password and the port and interface on which the container will listen for SSH connections. The .env file belongs in the top-level directory of the repo, since that is where the docker-compose command will be executed. 

For more information, see the official documentation: https://docs.docker.com/compose/env-file/

If you have any more questions, please let me know. Otherwise, we will close this issue.

**Comment by atanasj** [comment]
No, that's great. I'll give it a crack and let you know if I run into any more issues. Thanks for your help.
